/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorADR;
import Controlador.ControladorTickets;
import Modelo.Modelo;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author David Camacho, Beatriz Abad y Daniel Villegas
 */
public class VentanaListadoTickets extends javax.swing.JFrame {

    private Modelo modelo = new Modelo();
    private ControladorTickets listener;
    private DefaultListModel modeloLista;

    /**
     * Creates new form VentanaTickets
     */
    public VentanaListadoTickets(Modelo modelo) {
        this.setLocationRelativeTo(null);
        this.modelo = modelo;
        initComponents();
        cargarLayout();
        cargaLista();
        cargaListaTicket();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelCaso = new javax.swing.JLabel();
        jComboBoxCasos = new javax.swing.JComboBox<>();
        labelTickets = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTickets = new javax.swing.JList<>();
        botonAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCaso.setText("Seleccione un caso:");

        jComboBoxCasos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{}));

        labelTickets.setText("Tickets: ");

        modeloLista = new DefaultListModel();
        jListTickets.setModel(modeloLista);
        jScrollPane1.setViewportView(jListTickets);

        botonAceptar.setText("Aceptar");

        listener = new ControladorTickets(modelo, this);
        botonAceptar.addActionListener(listener);
        jComboBoxCasos.addActionListener(listener);

    }

    public JButton getBotonAceptar() {
        return botonAceptar;
    }

    public String getjComboBoxCasos() {
        return String.valueOf(jComboBoxCasos.getSelectedItem());
    }

    public String getjListTickets() {
        return jListTickets.getSelectedValue();
    }

    public void cargaLista() {
        getjComboBoxCasos();
        ArrayList<String> listaCasos = listener.getListaTicketBd();
        for (String string : listaCasos) {
            jComboBoxCasos.addItem(string);
        }
    }

    public boolean cargaListaTicket() {
        boolean vacio = false;
        ArrayList<String> listaTickets = listener.getListaTicketsCasos();
        modeloLista.clear();
        if (listaTickets == null) {
            JOptionPane.showConfirmDialog(null, "No hay tickets para mostrar");
            vacio = true;
        } else {
            for (String string2 : listaTickets) {
                modeloLista.addElement(string2);
            }
        }
        return vacio;
    }

    public void cargarLayout() {
        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(labelCaso)
                                                .addGap(18, 18, 18)
                                                .addComponent(jComboBoxCasos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelTickets)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 8, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(botonAceptar)))
                                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelCaso)
                                        .addComponent(jComboBoxCasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelTickets)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonAceptar)
                                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    private javax.swing.JButton botonAceptar;
    private javax.swing.JComboBox<String> jComboBoxCasos;
    private javax.swing.JList<String> jListTickets;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCaso;
    private javax.swing.JLabel labelTickets;

}
