package Vista;

import Controlador.ControladorEnviarEmail;

public class VentanaEnviarEmail extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form VistaEnviarEmail
	 */
	public VentanaEnviarEmail() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	private void initComponents() {

		mensajeLabel = new javax.swing.JLabel();
		jScrollPane1 = new javax.swing.JScrollPane();
		cuerpoTextArea = new javax.swing.JTextArea();
		btnEnviar = new javax.swing.JToggleButton();
		jLabelPara = new javax.swing.JLabel();
		textFieldPara = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
		jTextFieldAsunto = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		mensajeLabel.setText("Mensaje:");

		cuerpoTextArea.setColumns(20);
		cuerpoTextArea.setRows(5);
		jScrollPane1.setViewportView(cuerpoTextArea);

		btnEnviar.setText("Enviar");

		jLabelPara.setText("Para:");

		jLabel1.setText("Asunto:");

		ControladorEnviarEmail listener = new ControladorEnviarEmail(this);
		btnEnviar.addActionListener(listener);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(btnEnviar).addGap(43, 43, 43))
				.addGroup(layout.createSequentialGroup().addContainerGap().addGroup(layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jScrollPane1)
						.addGroup(layout.createSequentialGroup().addGroup(layout
								.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
								.addComponent(mensajeLabel)
								.addGroup(layout.createSequentialGroup().addComponent(jLabel1)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jTextFieldAsunto))
								.addGroup(layout.createSequentialGroup().addComponent(jLabelPara).addGap(18, 18, 18)
										.addComponent(textFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE, 276,
												javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addGap(0, 0, Short.MAX_VALUE)))
						.addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout
				.createSequentialGroup().addGap(18, 18, 18)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabelPara).addComponent(textFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(jLabel1)
						.addComponent(jTextFieldAsunto, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				.addGap(26, 26, 26).addComponent(mensajeLabel)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
				.addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168,
						javax.swing.GroupLayout.PREFERRED_SIZE)
				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(btnEnviar)
				.addGap(11, 11, 11)));

		pack();
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(VentanaEnviarEmail.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(VentanaEnviarEmail.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(VentanaEnviarEmail.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(VentanaEnviarEmail.class.getName()).log(java.util.logging.Level.SEVERE,
					null, ex);
		}

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new VentanaEnviarEmail().setVisible(true);
			}
		});
	}

	public String getCuerpoTextArea() {
		return cuerpoTextArea.getText();
	}

	public void setCuerpoTextArea(String cuerpoTextArea) {
		this.cuerpoTextArea.setText(cuerpoTextArea);
	}

	public String getTextFieldPara() {

		return textFieldPara.getText();
	}

	public void setTextFieldPara(String textFieldPara) {

		this.textFieldPara.setText(textFieldPara);
	}

	public String getjTextFieldAsunto() {
		return jTextFieldAsunto.getText();
	}

	public void setjTextFieldAsunto(String jTextFieldAsunto) {
		this.jTextFieldAsunto.setText(jTextFieldAsunto);
	}

	// Variables declaration - do not modify
	private ControladorEnviarEmail cee;
	private javax.swing.JToggleButton btnEnviar;
	private javax.swing.JTextArea cuerpoTextArea;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabelPara;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTextField jTextFieldAsunto;
	private javax.swing.JLabel mensajeLabel;
	private javax.swing.JTextField textFieldPara;
	// End of variables declaration
}