/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorCasos;
import Modelo.Modelo;
import javax.swing.JButton;
import javax.swing.JRadioButton;

/**
 *
 * @author David Camacho, Beatriz Abad y Daniel Villegas
 */
public class VentanaCasosADR extends javax.swing.JFrame {
    
    private Modelo modelo = new Modelo();

    /**
     * Creates new form VentanaCasosADR
     */
    public VentanaCasosADR() {
        initComponents();
        cargarLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        botonAceptar = new javax.swing.JButton();
        botonCancelar = new javax.swing.JButton();
        jRadioButtonCrearCaso = new javax.swing.JRadioButton();
        jRadioButtonContinuarCaso = new javax.swing.JRadioButton();
        grupoCaso = new javax.swing.ButtonGroup();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        botonAceptar.setText("Aceptar");
        botonCancelar.setText("Cancelar");

        jRadioButtonCrearCaso.setText("Crear caso");
        jRadioButtonContinuarCaso.setText("Continuar caso");
        
        grupoCaso.add(jRadioButtonContinuarCaso);
        grupoCaso.add(jRadioButtonCrearCaso);
        
        ControladorCasos listener = new ControladorCasos(modelo, this);
        botonAceptar.addActionListener(listener);
        botonCancelar.addActionListener(listener);

    }

    public JButton getBotonAceptar() {
        return botonAceptar;
    }

    public JButton getBotonCancelar() {
        return botonCancelar;
    }

    public JRadioButton getjRadioButtonContinuarCaso() {
        return jRadioButtonContinuarCaso;
    }

    public JRadioButton getjRadioButtonCrearCaso() {
        return jRadioButtonCrearCaso;
    }
    
    public void cargarLayout() {

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jRadioButtonContinuarCaso)
                                        .addComponent(jRadioButtonCrearCaso))
                                .addGap(59, 59, 59)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(botonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonAceptar)
                                        .addComponent(jRadioButtonCrearCaso))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(botonCancelar)
                                        .addComponent(jRadioButtonContinuarCaso))
                                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }


    private javax.swing.JButton botonAceptar;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonContinuarCaso;
    private javax.swing.JRadioButton jRadioButtonCrearCaso;
    private javax.swing.ButtonGroup grupoCaso;

}
